import React from "react";
import { View, Text, TouchableOpacity, SafeAreaView } from "react-native";
import { StatusBar } from "expo-status-bar";

export default function App() {
  return (
    <SafeAreaView className="flex-1 bg-white">
      <StatusBar style="dark" />
      <View className="p-6">
        <Text className="text-3xl font-bold text-gray-800 mb-2">FixGo</Text>
        <Text className="text-base text-gray-600 mb-6">
          Book quick fixes for your car anytime, anywhere.
        </Text>

        <TouchableOpacity className="bg-black rounded-2xl p-4">
          <Text className="text-white text-center text-base font-semibold">
            Book a Service
          </Text>
        </TouchableOpacity>
      </View>
    </SafeAreaView>
  );
}


